import Link from "next/link";
import { TurntableHero } from "@/components/TurntableHero";
import { ReleaseExplorer } from "@/components/ReleaseExplorer";
import { WorldSwitcher } from "@/components/WorldSwitcher";
import { releases } from "@/lib/releases";
export default function Home(){return <main>
<section className="hero"><div className="hero-copy"><p className="kicker">Jazz · Hip-hop · Global rhythms · Electronic</p><h1>Music for<br/><em>after dark.</em></h1><p>DJ Hotwax moves between velvet jazz rooms, coastal motion, heavy drums, and long-form electronic energy—one cinematic identity built around atmosphere.</p><div className="hero-actions"><Link className="primary" href="/music">Explore the catalog</Link><a className="text-link" href={releases[0].url} target="_blank" rel="noreferrer">Play latest album ▶</a></div><div className="hero-meta"><span>PHOENIX / AZ</span><span>INDEPENDENT SOUND</span><span>EST. AFTER DARK</span></div></div><TurntableHero/></section>
<section className="section"><div className="section-head"><div><p className="kicker">Now spinning</p><h2>Nuits Feutrées</h2></div><p>Late-night French jazz shaped by velvet rooms, rain-lit streets, and the hour when the city finally lowers its voice.</p></div><div className="latest-grid"><img src="/covers/nuits-wide.svg" alt="Nuits Feutrées visual artwork"/><div><span>LATEST ALBUM · 62 MINUTES</span><h3>Velvet light.<br/>Rain outside.<br/>No rush.</h3><a className="primary outline" href={releases[0].url} target="_blank" rel="noreferrer">Listen on YouTube ↗</a></div></div></section>
<section className="section black-section"><div className="section-head"><div><p className="kicker">Selected catalog</p><h2>Choose your hour.</h2></div><p>Move through the catalog as a set of visual worlds rather than a fixed genre shelf.</p></div><ReleaseExplorer/></section>
<section className="section"><div className="section-head"><div><p className="kicker">One name. Four worlds.</p><h2>Genre is the palette.<br/><em>Atmosphere is the signature.</em></h2></div><p>Every release lives inside a broader visual and sonic environment. Switch worlds to see how the identity changes without losing the DJ Hotwax signature.</p></div><WorldSwitcher/></section>
<section className="statement"><small>INDEPENDENT SOUND, WITHOUT BORDERS</small><h2>From a Paris lounge to a Havana night, a California drive to a warehouse at 2 A.M.</h2><p>That is the DJ Hotwax universe.</p></section>
<section className="cta-band"><div><small>PLACEMENTS · LICENSING · CREATIVE WORK</small><h2>Put the right sound<br/>in the right world.</h2></div><Link className="primary" href="/licensing">Work with DJ Hotwax ↗</Link></section>
</main>}
